### ISSUE TITLE
这个代码跑步起来啊，

### ISSUE THREAD

**Issue by iphone5s** [zhoujunhe/aid#4]

**Comment by zhoujunhe** [comment]
> 操作系统：Windows 10 iTunes版本：12.5.3.16 （x64） 手机型号：iPhone 6 plus 金色 手机系统版本：10.1.1
> 
> 实在找不到iOS10.1.1 的系统。。。我在iOS 14下测试了。无法开启同步。而且连接也有很多问题。。 能否适配一下 14 付高价报酬。。[453742103@qq.com](mailto:453742103@qq.com) 这个是我的邮箱。。急需。可先付费

已经 Releases v1.0.0-beta 版本，你可以直接下载一来测试一下，直接调用编译好的aid.dll 函数好了
